services:
  - type: web
    name: londono-service
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node Server.js
    envVars:
      - key: TFL_APP_KEY
        sync: false
